package com.food.entities;

public enum RequestStatus {

	ACTIVE, PENDING, MATCHED, COMPLETED, SUBMITTED, CANCELLED, DRAFT, APPROVED, REJECTED, MARKED_FOR_WASTE,
	WASTE_ASSIGNED, WASTE_COLLECTED, WASTE_PROCESSED,
}
